version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27015:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - custom-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/product-service-db
    volumes:
      - ./src:/app/src  # Adjust this to match your project structure
    networks:
      - custom-net

volumes:
  mongo-data:

networks:
  custom-net:
